#!/bin/bash
killall conky
# conky -c ~/.conky/conkybar_v2/configs/conky_bg &
conky -p 2 -c ~/.conky/conkybar_v2/configs/conky_network &
conky -p 4 -c ~/.conky/conkybar_v2/configs/conky_system &
conky -p 6 -c ~/.conky/conkybar_v2/configs/conky_cpu &
conky -p 8 -c ~/.conky/conkybar_v2/configs/conky_ram &
conky -p 10 -c ~/.conky/conkybar_v2/configs/conky_files &
# conky -p 12 -c ~/.conky/conkybar_v2/configs/conky_banshee &
conky -p 14 -c ~/.conky/conkybar_v2/configs/conky_clock &
conky -p 15 -c ~/.conky/conkybar_v2/configs/conky_txt
exit